### PR TITLE
Radio Beacons

### PR DESCRIPTION
**Pull request by audax**
Sorry for the whitespace errors. Should we include the need for a sound file in the Readme? Also: This version is not finally tested, I only tested the version integrated in the shagratdcs repository. Either you do a final check with the demo mission or I do it in the next days.

### CODE REVIEW

**Comment by ciribob** [comment]
Ah no worries!

I'd include the sound file as well just to make it easier to use.

I probably won't have time to test till the weekend so I'll wait till
either I or you test it if thats ok? :)

I'm so happy the radio beacons are working again, I wonder why they didn't
mention in the patch notes!

Thanks again!

On Tue, Jun 2, 2015 at 2:43 PM, Jens Kadenbach <notifications@github.com>
wrote:

> Sorry for the whitespace errors. Should we include the need for a sound
> file in the Readme? Also: This version is not finally tested, I only tested
> the version integrated in the shagratdcs repository. Either you do a final
> check with the demo mission or I do it in the next days.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ciribob/DCS-Medevac/pull/7
> Commit Summary
>
>    - Radio Beacons
>
> File Changes
>
>    - *M* Medevac_CSAR.lua
>    <https://github.com/ciribob/DCS-Medevac/pull/7/files#diff-0> (304)
>    - *M* medevac-demo.miz
>    <https://github.com/ciribob/DCS-Medevac/pull/7/files#diff-1> (0)
>
> Patch Links:
>
>    - https://github.com/ciribob/DCS-Medevac/pull/7.patch
>    - https://github.com/ciribob/DCS-Medevac/pull/7.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciribob/DCS-Medevac/pull/7>.
>



-- 
Regards,

Ciaran

**Comment by ciribob** [comment]
Are you happy for me to merge? Sorry, didn't get round to testing this!

**Comment by audax** [comment]
I didn't get to test it either, our Sunday flight was canceled.

**Comment by ciribob** [comment]
I should have some to time next sunday if you don't get time :)

**Comment by ciribob** [comment]
I only managed a quick test but seemed to work. Thanks again!

**Pull request merged**
