### PR TITLE
Dynamic max_units depending on the loadout

### PR DESCRIPTION
**Pull request by audax**
Calculate the maximum amount of units a helicopter can carry by looking at the loadout. The amount of units is calculate if the helicopter takes of for the first time and every time the pilot saves the loadout with F10-F2.

### CODE REVIEW

**Comment by ciribob** [comment]
Audax, thats incredible. Nice Job! 

Sorry I didnt get notified by GitHub of this... I just saw on the forums, you're going to do a big test on Sunday? 

In other news, I've been playing around with Beacons ever since you tried. An old DCS function is now working for me in multiplayer. It will broadcast on the FM radio (not the other ADF one) for the Huey, just set the far right knob on the radio to home and the frequency to 46.00

Try:

trigger.action.radioTransmission("soundfile.ogg", _unitPoint, 1, true, 46000000, 1000)

**Comment by audax** [comment]
even with the trigger.action.radioTransmission it doesn't work. I get a signal but the homing mode leads me to another position, not the units position. I'll give up for now. If you can make it work, I'll send you a teddy bear!

**Comment by audax** [comment]
The only bug we could find was that you can't open the medevac list until you saved your loadout by taking off or manually.

Also, suddenly the radio beacons stuff just works. The original pull request I sent.

**Comment by ciribob** [comment]
Awesome, i'll merge this then. Thanks!

Are you going to issue a separate request with the Radio beacon stuff again?

**Pull request merged**
